version: '3.9'

services:
   # Php Service
  php:
    image: wodby/php:latest
    volumes:
      - './:/var/www/html'
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 88:80
    links:
      - 'php'
    volumes:
      - './:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: Portfolio2024!
      MYSQL_ROOT_PASSWORD: R00tp@ss
    ports:
      - 3308:3306

  # phpmyadmin in an external image
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: R00tp@ss
    ports:
      - "1088:80"

  # wordpress
  wordpress:
    image: wordpress:latest
    container_name: prog_m5_wordpress
    environment:
      WORDPRESS_DB_HOST: '${SERVERNAME}'
      WORDPRESS_DB_NAME: '${DBNAME}'
      WORDPRESS_DB_USER: '${USERNAME}'
      WORDPRESS_DB_PASSWORD: '${PASSWORD}'
    ports:
      - "9999:80"
    volumes:
      - './themes:/var/www/html/wp-content/themes'
      - './plugins:/var/www/html/wp-content/plugins'
      - './uploads:/var/www/html/wp-content/uploads'
    depends_on:
      - mariadb